### ISSUE TITLE
Does this still work??

### ISSUE THREAD

**Issue by blender-tv-studio** [gnuton/mixamo_anims_downloader#9]
If you could just let us know the state here of github repository. If it'll still work.people could easily see that when they look at this seven year old repository... thanks!!!

**Comment by gnuton** [comment]
does it work for you?

**Comment by blender-tv-studio** [comment]
I haven't tried it I was just wondering if this repository was still
maintained if it was even worth my time to try it

**Comment by gnuton** [comment]
do not try

**Comment by blender-tv-studio** [comment]
Ok, no problem. Yeah I'm rewriting it myself anyway so it pulls the
information directly from the website

**Comment by gnuton** [comment]
Makes sense.. rewriting from scratch is faster then trying something out.

**Comment by gnuton** [comment]
no sense chat. closing.
